### PR TITLE
fix(radio): missing watcher for value

### PR DESCRIPTION
**Pull request by tychenjiajun**

### CODE REVIEW

**Comment by tychenjiajun** [comment]
@matsp There's one thing I don't understand: What's the `picked` here?
```
  model: {
    prop: 'picked',
    event: 'change'
  }
```

**Comment by matsp** [comment]
@tychenjiajun checkbox is using "checked" as property for its states. v-model is ignoring initial values on standard input properties so i had to rename it to "picked". Otherwise you are not able to have inital enabled checkboxes.

https://vuejs.org/v2/guide/forms.html

**Comment by tychenjiajun** [comment]
@matsp It can be I guess. MDC-Web seems to allow users to do so by setting `value` of `MDCRadio`.

I asked the question about `picked` because I didn't see the `picked` property the `props`.

**Comment by matsp** [comment]
@tychenjiajun When you define:

```javascript
model: {
  prop: 'picked',
  event: 'change'
}
```

and "v-model" in your template, the "change" event value will be passed to the v-modeled prop. You can give your model prop a random name. In this case "picked" is simply not needed in the component itself because we just need the radio value outside of the component.

**Comment by tychenjiajun** [comment]
@matsp Thank you for your explanation!

**Pull request merged**
