### PR TITLE
Updated to material-components-web 1.0.1

### PR DESCRIPTION
**Pull request by tychenjiajun**
# Changelist 
- Upgrade all dependencies.
- Add demos for all components in doc.

## Chip

- Add event listener for `@MDCChip:trailingIconInteraction`

## Dialog

- Add prop `stacked` for `autoStackButtons`
- Add slot observer to add specific classes to action buttons.

## Drawer

- Rewrite
- Add `m-drawer-scrim` for drawer modal
- Add `m-drawer-list` for `<nav class='mdc-list>`

## Floating Label

- Use `<span>` when parent is `<m-select>`

## Icon

- Use `<span>` in `<li`>(`<m-list-item>`) or `<m-tab>`
- Use `<button>` in `<m-top-app-bar>`

## Icon Button

- Fix the bug that the `slotObserver` do not disconnect in `beforeDestroy`

## Image List

- Change `masonryColumn` and `standardColumn` to `masonry` and `column`

## Line Ripple

- Add props `activate` and `rippleCenter`

## Linear Progress

- Give default value for props

## List

- Add instantiate codes
- Add props `singleSelection`, `vertical`, `wrapFocus`
- Change `<m-list-group-subheader>` to `<h6>` or `<h3>`

## List Item

- Use `<a>` if prop `href` given

## Menu

- Add pros `anchorCorner`, `absolutePositionX`, `absolutePosition`, `fixed` and `wrapFocus`
- Add menu surface

## Notched Outline

- Rewrite

## Select

- Rewrite

## Snackbar

- Rewrite

## Tab

- Rewrite

## Text Field

- Rename from `Textfield`
- Rewrite

## Top App Bar

- Seperate title from content. Move default slots out of the title.

# TODOs

- Docs

### CODE REVIEW

**Comment by tychenjiajun** [comment]
@rchan well wait there's still errors and lack of docs. I'm fixing...

**Comment by tychenjiajun** [comment]
Please see http://cdn.deeloves.me to view the demos

**Comment by matsp** [comment]
Wow there is a lot work in it!! Can you also fix the snapshots and probably add more tests in the future?

**Comment by tychenjiajun** [comment]
@matsp It takes me time to learn snapshot testing. I'm working on it.

**Comment by tychenjiajun** [comment]
@matsp When will a new version release?

**Comment by matsp** [comment]
I have low bandwidth internet in South Africa these days but hopefully it's better tomorrow evening. I try to put out a alpha version which you can test.

**Comment by matsp** [comment]
BTW if you want you can also update the badge in the README for the user mdc-web version.

**Comment by matsp** [comment]
BTW if you want you can also update the badge in the README for the user mdc-web version.

**Comment by tychenjiajun** [comment]
> I have low bandwidth internet in South Africa these days but hopefully it's better tomorrow evening. I try to put out a alpha version which you can test.

An alpha version will be great. I suggest using a major version like `1.0.0.alpha`

**Comment by matsp** [comment]
I had this in my mind too. Trying now to release a  version from my phone - not so easy ;-)

**Pull request merged**
