### PR TITLE
feat(card): add primary action component

### PR DESCRIPTION
**Pull request by tychenjiajun**
#287

### CODE REVIEW

**Comment by matsp** [comment]
@tychenjiajun In the case of switching from normal card to primary action card at runtime, I would have to duplicate the component and render conditionally by a prop?

**Comment by tychenjiajun** [comment]
@matsp Yes.

**Comment by matsp** [comment]
@tychenjiajun Didn't see the benefit yet. The user will experience more markup. To have it all in one component is more complex for us but the user will benefit from it by writing less. Maybe I am missing something. Can you describe your idea to split it? I just want to be sure to find the right balance between development and end user experience :sweat_smile:

**Comment by tychenjiajun** [comment]
@matsp And considering accessibility, it's hard to bind a keydown event to the actionable content.

**Comment by tychenjiajun** [comment]
@matsp We can also keep an `actionable` prop and use conditional rendering to provide a better user experience. When `actionable` is true, render a built-in `mdc-card__primary-action` and bind all the event listeners to it. In this way, users can choose either `actionable` prop or an independent and highly customizable `<m-card-primary-action>` component.

**Pull request merged**
