### PR TITLE
Fix some bugs of both code and document description.

### PR DESCRIPTION
**Pull request by ctuu**
code in **shape** component has a bug.
the document descriptions of  **textfield** and **icon-button** components have bugs

### CODE REVIEW

**Comment by matsp** [comment]
@ctuu Thanks for catching these issues :)

**Comment by matsp** [comment]
@ctuu Can you split the commit in three?

* fix(shape): Property typo
* docs(textfield): Fix examples
* docs(icon-button): Fix slot description

**Comment by ctuu** [comment]
@matsp  ok i will try to do it.

**Comment by ctuu** [comment]
@matsp It seems that the commit now be split into three commits.

**Comment by matsp** [comment]
Thanks!:blush:

**Pull request merged**
