### PR TITLE
fixes for mdc-web v0.38 breaking changes

### PR DESCRIPTION
**Pull request by rchan**

### CODE REVIEW

**Comment by matsp** [comment]
@rchan Thanks! Sorryfor the delay - I will have a look at it :+1:

**Comment by rchan** [comment]
@matsp I've added further fixes to Drawer, Menu and Dialog to fix breaking changes for mdc-web 0.39, 0.40 and 0.41 releases

Drawer includes moving to use Permanent, Dismissible and Modal naming convention

**Comment by matsp** [comment]
@rchan Can you also provide the documentation updates? Can you also implement the additional features that were added? Iam actually out of time because of my daily job, so I am stuck here..

**Comment by rchan** [comment]
documentation already changed where required

**Comment by rchan** [comment]
@tychenjiajun 
`<div class="mdc-drawer-scrim"></div>`
this needs to sit outside of the aside rendered by the component, so I'm unsure how to add it as part of component, perhaps we can add to documentation?

**Comment by matsp** [comment]
@rchan  Maybe add an extra component.

**Comment by rchan** [comment]
@matsp do you mean, instead of documenting it as
```
<m-drawer-modal v-model="isDrawerOpen">
 ....
</m-drawer-modal>
<div class="mdc-drawer-scrim"></div>
```
we do
```
<m-drawer-modal v-model="isDrawerOpen">
 ....
</m-drawer-modal>
<m-drawer-scrim/>
```
or is there a way to embed the scrim into the component?

**Comment by rchan** [comment]
@matsp the menu issue @tychenjiajun highlighted needs fixing, shall I create a new issue for it?

**Pull request merged**
